kind: pipeline
type: docker
name: default

steps:
  - name: build-and-push
    image: plugins/docker
    settings:
      registry: 10.24.36.10:30080
      repo: 10.24.36.10:30080/wulpy/orange-uptime-kuma-management-tool
      tags:
        - ${DRONE_COMMIT_SHA}
        - latest
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      insecure: true
    when:
      event:
        - push

  - name: build-dry-run
    image: plugins/docker
    settings:
      registry: 10.24.36.10:30080
      repo: 10.24.36.10:30080/wulpy/orange-uptime-kuma-management-tool
      dry_run: true
      insecure: true
    when:
      event:
        - pull_request
