kind: pipeline
type: docker
name: default

trigger:
  event:
    - push
    - pull_request
  branch:
    - main

steps:
  - name: build-and-push
    image: plugins/docker
    settings:
      registry:
        from_secret: GITEA_REGISTRY
      repo:
        from_secret: MGMT_IMAGE_REPO
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:7}
      build_args:
        - BUILD_VERSION=${DRONE_COMMIT_SHA:0:7}
      username:
        from_secret: GITEA_REGISTRY_USERNAME
      password:
        from_secret: GITEA_REGISTRY_PASSWORD
      insecure: true
    when:
      event:
        - push

  - name: build-dry-run
    image: plugins/docker
    settings:
      registry:
        from_secret: GITEA_REGISTRY
      repo:
        from_secret: MGMT_IMAGE_REPO
      dry_run: true
      insecure: true
    when:
      event:
        - pull_request
